### ISSUE TITLE
Pytest action fails

### ISSUE THREAD

**Issue by lmarini** [clowder-framework/clowder2#158]
```
Run pipenv run pytest -v
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/pipenv/core.py", line 2680, in _launch_windows_subprocess
n subprocess.Popen([command] + script.args, **options)
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/.local/share/virtualenvs/backend-yQwxK-bj/bin/pytest'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.15/x64/bin/pipenv", line 8, in <module>
    sys.exit(cli())
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/pipenv/vendor/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/pipenv/cli/options.py", line 57, in main
    return super().main(*args, **kwargs, windows_expand_args=False)
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/pipenv/vendor/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/pipenv/vendor/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/pipenv/vendor/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/pipenv/vendor/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/pipenv/vendor/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/pipenv/vendor/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/pipenv/cli/command.py", line 421, in run
    do_run(
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/pipenv/core.py", line 2780, in do_run
    run_fn(*run_args, **run_kwargs)
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/pipenv/core.py", line 2690, in do_run_nt
    p = _launch_windows_subprocess(script, env)
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/pipenv/core.py", line 2682, in _launch_windows_subprocess
    if e.winerror != 193:
AttributeError: 'FileNotFoundError' object has no attribute 'winerror'
Error: Process completed with exit code 1.
```

**Comment by lmarini** [comment]
Updating actions/cache to v2 did the trick.
