### ISSUE TITLE
pytest error

### ISSUE THREAD

**Issue by tcnichol** [clowder-framework/clowder2#246]
Some of the tests are failing on some pull requests. This is the beginning of the error:

`Run pipenv run pytest -v
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/pipenv/core.py", line 2739, in _launch_windows_subprocess
n subprocess.Popen([command] + script.args, **options)
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.9.[16](https://github.com/clowder-framework/clowder2/actions/runs/3707688397/jobs/6284399647#step:9:17)/x64/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/.local/share/virtualenvs/backend-yQwxK-bj/bin/pytest'

During handling of the above exception, another exception occurred:`

**Comment by longshuicy** [comment]
linked to #563
