### ISSUE TITLE
upgrade keycloak

### ISSUE THREAD

**Issue by tcnichol** [clowder-framework/clowder2#891]
Upgrade keycloak to v20.

**Comment by markendr** [comment]
Hi, as per clowder slack general channel, we need a [keycloak fix](https://github.com/keycloak/keycloak/issues/18057) in v20 so we can setup keycloak to go straight to our openidc idp (no username/password, registration form). Attempting to update the keycloak browser flow in v19 (Configure -> Authentication -> Flows -> browser -> idp redirector -> settings) gives error..

![image](https://github.com/clowder-framework/clowder2/assets/18689435/66cd9faf-3c56-4839-ae6f-fb19b7cae8e3)

I tried updating Chart.yaml to install keycloak v20 by updating dependencies..
```
dependencies:
...
  - name: keycloak
    version: ~13
...
```
Keycloak 20.0.5 installs okay, the existing (19.0.3) realm.json seems to load okay, and the keycloak authenticator issue is resolved. ie. I can set a default idp and the keycloak username/password/registration page is no longer displayed, and I can login with idp, but clowder2-backend gives "Internal Server Error"..
```
INFO:     <ip:port> - "GET /api/v2/auth?session_state=81d0f336-91c9-4984-9492-eb657283f78e&code=16134a23-f1c3-4e8c-ac61-8a3cd4355e13.81d0f336-91c9-4984-9492-eb657283f78e.54c87ecc-a8ef-45a1-9ec3-b4a42ddb8b7a HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/code/.venv/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 429, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/code/.venv/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/code/.venv/lib/python3.9/site-packages/fastapi/applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "/code/.venv/lib/python3.9/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/code/.venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/code/.venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/code/.venv/lib/python3.9/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/code/.venv/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/code/.venv/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/code/.venv/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/code/.venv/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/code/.venv/lib/python3.9/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/code/.venv/lib/python3.9/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/code/.venv/lib/python3.9/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/code/.venv/lib/python3.9/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "/code/.venv/lib/python3.9/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "/code/app/routers/keycloak.py", line 115, in auth
    userinfo = keycloak_openid.userinfo(access_token)
  File "/code/.venv/lib/python3.9/site-packages/keycloak/keycloak_openid.py", line 401, in userinfo
    return raise_error_from_response(data_raw, KeycloakGetError)
  File "/code/.venv/lib/python3.9/site-packages/keycloak/exceptions.py", line 192, in raise_error_from_response
    raise error(
keycloak.exceptions.KeycloakGetError: 403: b''
```

**Comment by tcnichol** [comment]
I am getting the same error. This seems to sort of explain what is going on 
https://github.com/keycloak/keycloak/pull/14237

**Comment by tcnichol** [comment]
More info at this link
https://keycloak.discourse.group/t/issue-on-userinfo-endpoint-at-keycloak-20/18461/4

**Comment by tcnichol** [comment]
Here is a video that shows how to add openid in keycloak to fix the error that is happening with keycloak v20.

I have not figured out how to change the config for keycloak so that this step is not needed yet.


https://github.com/clowder-framework/clowder2/assets/40038535/55aee58a-8c23-4b5b-b23a-4e716c3dba94
